// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "dartjni.h"
#include "jni.h"

thread_local JNIEnv* jniEnv;
JniContext* jni;

JniContext* (*context_getter)(void);
JNIEnv* (*env_getter)(void);

void setJniGetters(JniContext* (*cg)(void), JNIEnv* (*eg)(void)) {
  context_getter = cg;
  env_getter = eg;
}

// BatteryPlusPlugin
jclass _c_BatteryPlusPlugin = NULL;

jmethodID _m_BatteryPlusPlugin__getApplicationContext = NULL;
FFI_PLUGIN_EXPORT
JniResult BatteryPlusPlugin__getApplicationContext(jobject self_) {
  load_env();
  load_class_global_ref(&_c_BatteryPlusPlugin, "BatteryPlusPlugin");
  if (_c_BatteryPlusPlugin == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_BatteryPlusPlugin,
              &_m_BatteryPlusPlugin__getApplicationContext,
              "getApplicationContext", "()Landroid/app/Activity;");
  if (_m_BatteryPlusPlugin__getApplicationContext == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->CallObjectMethod(
      jniEnv, self_, _m_BatteryPlusPlugin__getApplicationContext);
  return to_global_ref_result(_result);
}

jmethodID _m_BatteryPlusPlugin__setApplicationContext = NULL;
FFI_PLUGIN_EXPORT
JniResult BatteryPlusPlugin__setApplicationContext(jobject self_,
                                                   jobject activity) {
  load_env();
  load_class_global_ref(&_c_BatteryPlusPlugin, "BatteryPlusPlugin");
  if (_c_BatteryPlusPlugin == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_BatteryPlusPlugin,
              &_m_BatteryPlusPlugin__setApplicationContext,
              "setApplicationContext", "(Landroid/app/Activity;)V");
  if (_m_BatteryPlusPlugin__setApplicationContext == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(
      jniEnv, self_, _m_BatteryPlusPlugin__setApplicationContext, activity);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_BatteryPlusPlugin__ctor = NULL;
FFI_PLUGIN_EXPORT
JniResult BatteryPlusPlugin__ctor(jobject activity) {
  load_env();
  load_class_global_ref(&_c_BatteryPlusPlugin, "BatteryPlusPlugin");
  if (_c_BatteryPlusPlugin == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_BatteryPlusPlugin, &_m_BatteryPlusPlugin__ctor, "<init>",
              "(Landroid/app/Activity;)V");
  if (_m_BatteryPlusPlugin__ctor == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->NewObject(jniEnv, _c_BatteryPlusPlugin,
                                         _m_BatteryPlusPlugin__ctor, activity);
  return to_global_ref_result(_result);
}

jmethodID _m_BatteryPlusPlugin__getBatteryLevel = NULL;
FFI_PLUGIN_EXPORT
JniResult BatteryPlusPlugin__getBatteryLevel(jobject self_) {
  load_env();
  load_class_global_ref(&_c_BatteryPlusPlugin, "BatteryPlusPlugin");
  if (_c_BatteryPlusPlugin == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_BatteryPlusPlugin, &_m_BatteryPlusPlugin__getBatteryLevel,
              "getBatteryLevel", "()Ljava/lang/String;");
  if (_m_BatteryPlusPlugin__getBatteryLevel == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->CallObjectMethod(
      jniEnv, self_, _m_BatteryPlusPlugin__getBatteryLevel);
  return to_global_ref_result(_result);
}

jmethodID _m_BatteryPlusPlugin__getBatteryStatus = NULL;
FFI_PLUGIN_EXPORT
JniResult BatteryPlusPlugin__getBatteryStatus(jobject self_) {
  load_env();
  load_class_global_ref(&_c_BatteryPlusPlugin, "BatteryPlusPlugin");
  if (_c_BatteryPlusPlugin == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_BatteryPlusPlugin, &_m_BatteryPlusPlugin__getBatteryStatus,
              "getBatteryStatus", "()Ljava/lang/String;");
  if (_m_BatteryPlusPlugin__getBatteryStatus == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->CallObjectMethod(
      jniEnv, self_, _m_BatteryPlusPlugin__getBatteryStatus);
  return to_global_ref_result(_result);
}

jmethodID _m_BatteryPlusPlugin__isInPowerSaveMode = NULL;
FFI_PLUGIN_EXPORT
JniResult BatteryPlusPlugin__isInPowerSaveMode(jobject self_) {
  load_env();
  load_class_global_ref(&_c_BatteryPlusPlugin, "BatteryPlusPlugin");
  if (_c_BatteryPlusPlugin == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_BatteryPlusPlugin, &_m_BatteryPlusPlugin__isInPowerSaveMode,
              "isInPowerSaveMode", "()Ljava/lang/Boolean;");
  if (_m_BatteryPlusPlugin__isInPowerSaveMode == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->CallObjectMethod(
      jniEnv, self_, _m_BatteryPlusPlugin__isInPowerSaveMode);
  return to_global_ref_result(_result);
}

jfieldID _f_BatteryPlusPlugin__Companion = NULL;
FFI_PLUGIN_EXPORT
JniResult get_BatteryPlusPlugin__Companion() {
  load_env();
  load_class_global_ref(&_c_BatteryPlusPlugin, "BatteryPlusPlugin");
  if (_c_BatteryPlusPlugin == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_static_field(_c_BatteryPlusPlugin, &_f_BatteryPlusPlugin__Companion,
                    "Companion", "LBatteryPlusPlugin$Companion;");
  jobject _result = (*jniEnv)->GetStaticObjectField(
      jniEnv, _c_BatteryPlusPlugin, _f_BatteryPlusPlugin__Companion);
  return to_global_ref_result(_result);
}
